[build]
  publish = "."

[context.deploy-preview]
  command = "echo 'skip'"

[context.branch-deploy]
  command = "echo 'skip'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

